### ISSUE TITLE
ENH: a simple tool for openpyxl

### ISSUE THREAD

**Issue by esocraton** [esocraton/openpyxl_fork#1]
**FEATURE TYPE**

- [X] Adding new functionality
- [ ] Changing existing functionality
- [ ] Removing existing functionality

**DESCRIPTION**
An excel comparator can be coded to compare excel files. 

**TO-DO**
- [X] Codding the functionality
- [ ] Modulating the functionality
- [ ] Error detection in functionality
- [ ] Placing the functionality
